### ISSUE TITLE
adapter.find(**{'port-element-id': int}) fails with NotFound Error

### ISSUE THREAD

**Issue by scheuran** [zhmcclient/python-zhmcclient#125]
### Actual behavior
Searching for an adapter port along it's element-id reluts in NotFound Error when passing the element-id as integer. (It works fine when passing it as string.)

### Expected behavior
Searching for a port along port-element-id succeeds when input is an integer.

### Execution environment
cpc = client.cpcs.find(name="CPC")
adapters = cpc.adapters.findall(**{'type': 'osd'})
for adapt in adapters:
  adapt.pull_full_properties()
  print adapt.ports.find(**{'element-id': 0})

* zhmcclient version: 0.7.0
* Operating system (type+version): ubuntu14, intel, vagrant vm

**Comment by andy-maier** [comment]
The `element-id` property of a network port resource is of type String(1-2), see section "Network Port element object" in the HMC API book. So it is not unexpected that it doesn't work with an integer as input.

We should discuss whether handling the integer input with a `zhmcclient.NotFound` exception is reasonable, because as a Python user I would expect a `TypeError` exception in such a case, instead.

**Comment by andy-maier** [comment]
We discussed this and Andreas agreed that this is no issue. Closing it.

**Comment by scheuran** [comment]
What about the idea of returning an invalid parameter type error or so?

**Comment by andy-maier** [comment]
That would need to be done in the HMC, because the zhmcclient does not know any properties except name, id and uri.
