### ISSUE TITLE
Bad return for LPAR initial-processing-weight

### ISSUE THREAD

**Issue by Tam-Lin** [zhmcclient/python-zhmcclient#156]
### Actual behavior

According to the book, at least, initial-processing-weight should be the initial weight, or 0 if the LPAR doesn't have any shared GCPs defined.  However, for an image with no shared GCPs defined (a CF, for example), initial-processing-weight is returning None.

initial_lpar_weight = lpar.get_property('initial-processing-weight')
print "\t" + str(initial_lpar_weight)

The above returns None for a CF.

### Expected behavior

The book says it should return 0.  I don't know if this is a problem with the book/HMC or with zhmcclient.

### Execution environment

* zhmcclient version:  0.9.0
* Operating system (type+version):  Mac OS 10.12.2

**Comment by leopoldjuergen** [comment]
In which status is your LPAR ? When the LPAR is in status 'not-activated' I also get 'None' for lpar.get_property('initial-processing-weight'). But if I activate the LPAR I get a value for  lpar.get_property('initial-processing-weight').  Before activation of the LPAR you can get the property 'initial-processing-weight' from the image-activation-profile of the LPAR. You can have a look into the  activation_profiles.py example in the examples folder to see how to deal with activation_profiles.

**Comment by andy-maier** [comment]
Kevin,
The HMC API book for 2.13.1 has foot notes 1,2,3 on the table entry for "initial-processing-weight". Foot notes 1 and 3 read:

* 1. If the logical partition status property is "not-activated", a null object is returned instead of the documented
field type.
* 3. The value returned from a Get request is a null object for an object-id that does not represent a logical
partition with at least one not dedicated general purpose processor.

The JSON null object mentioned in the foot note is represented as `None` in Python. So the behavior you see seems to be in sync with the book and is backed by foot note 3. The behavior Juergen mentioned with not activated LPARs is backed by foot note 1.

**Comment by Tam-Lin** [comment]
I'll have to take this up with the HMC API folks, I guess.  I agree that's what the footnote says, but it seems to contradict the description column, which says it will return 0 if "The object-id does not represent a logical partition with at least one shared general purpose processor."  So the description column says an LPAR  without at least one shared GP will return 0, but the footnote says that the same LPAR will return a Null value.

**Comment by andy-maier** [comment]
I agree with your point of view...

**Comment by Tam-Lin** [comment]
Closing item; will discuss with HMC API folks.
