### ISSUE TITLE
Performance issue with "find()" when filtering on "object-id"

### ISSUE THREAD

**Issue by pranjank** [zhmcclient/python-zhmcclient#261]
Is "find" method is iterates over items?

For example
cpc.adapters.find(**{'object-id': 'xxxxxxxx'})

If it iterates over items then we should have DPM API to filter item for better performance.

**Comment by andy-maier** [comment]
The `find(`) method supports all properties as filter arguments. For those properties where the HMC supports server-side filtering via query parameters in the URI, this is exploited by the zhmcclient. The remaining properties are filtered on the client side in the zhmcclient code. If the set of filter argument contains properties for server-side filtering and properties for client-side filtering, they are split up and handled accordingly. As a special case, if the only filter argument is the `name` property, a client-side name-to-URI cache is used. Overall, that is the best the zhmcclient can do, IMO.

The properties that are filtered on the server side are listed in the `{Resource}Manager.query_props` attribute. For example, partitions support the `name` and `status` properties as query parameters. If you have a need to filter by some other property, and if you do that often, and if the selectivity of that property is high, we can talk with HMC development to get an additional property supported for server-side filtering.

`object-id` (or `element-id`) is not a property that the HMC supports for server-side filtering for any resource class. I assume the reason is that the resource URI can be built directly from the object ID. If you have a need to transform the object ID into a resource URI, please let us know; that could be provided by the zhmcclient. However, I'd also like to understand where that need comes from, because the HMC references resources always by URI, as far as I recall (e.g. `nic-uris` property in Partition).

**Comment by andy-maier** [comment]
PR #262 improves the description of the "Filtering" section and of the `find()`, `findall()`, and `list()` methods. Please verify whether that makes it clear now.

**Comment by andy-maier** [comment]
While writing a script to check out the performance of `find()`, I found a bug in the latest master code where `nics.find(name)` raises `NotFound` for an existing resource. I have opened issue #264 for that.

**Comment by andy-maier** [comment]
Another issue I found was that for some resource classes (e.g. CPCs and Adapters), `find(object-id)` performs a "List {Resource}" operation (which provides the object-id in its list result), but in addition the "Get {Resource} Properties" operation is performed for each resource in the list result in order to get the object-id. The invocation of the "Get {Resource} Properties" operations is not necessary given that the list operation already returns the object-id properties, and should be eliminated. I have opened issue #265 for that.

**Comment by andy-maier** [comment]
Issue #267 describes another bug I found in `find()` etc.

**Comment by andy-maier** [comment]
We made some performance measurements, and the main issue is this:
* For filtering by object-id (a property that is not filtered on the server side), the "List {Resource}s" operation is followed by a loop of "Get {Resource} Properties" operations, in order to get the object-id property, because it is not in the List result. That burns quite some time.
* This could be improved in either of two ways:
  - Add object-id to the properties returned by the List operations. We are discussing this internally.
  - Add a id-to-URI cache in the zhmcclient. This could be an extension to the existing name-to-URI cache.

**Comment by andy-maier** [comment]
Internal discussion resulted in the direction to implement support for transforming an `object-id` filter argument to `find()`, `findall()` or `list()` into an `object-uri` and specifying that as a filter query parameter on the URI of the `List <Resource>s` operation.

**Comment by andy-maier** [comment]
The remaining issue with this is fixed in PR #329.
