### ISSUE TITLE
zhmc lpar activate api timeout

### ISSUE THREAD

**Issue by sean-mills** [zhmcclient/python-zhmcclient#755]
**Describe the bug**
After using the LPAR activate function, no response is received and it times out after 900 seconds. However, after checking the operating system messages, it appears to have activated normally. The parameter, wait_for_completion, was set to true.

This is also apparent when using the zhmccli.

Output in Python:
```
Starting activation!
Traceback (most recent call last):
  File "/Users/tomas/ssc_projects/zrobot/zRobot_SSCVERIF/tests/scsi_load_python.py", line 13, in <module>
    lpar.activate(wait_for_completion=True, operation_timeout=None, status_timeout=None, allow_status_exceptions=True, activation_profile_name=None, force=True)
  File "<decorator-gen-26>", line 2, in activate
  File "/Users/tomas/.conda/envs/zRobot/lib/python3.7/site-packages/zhmcclient/_logging.py", line 223, in log_api_call
    result = func(*args, **kwargs)
  File "/Users/tomas/.conda/envs/zRobot/lib/python3.7/site-packages/zhmcclient/_lpar.py", line 326, in activate
    self.wait_for_status(statuses, status_timeout)
  File "<decorator-gen-36>", line 2, in wait_for_status
  File "/Users/tomas/.conda/envs/zRobot/lib/python3.7/site-packages/zhmcclient/_logging.py", line 223, in log_api_call
    result = func(*args, **kwargs)
  File "/Users/tomas/.conda/envs/zRobot/lib/python3.7/site-packages/zhmcclient/_lpar.py", line 1257, in wait_for_status
    actual_status, statuses, status_timeout)
zhmcclient._exceptions.StatusTimeout: Waiting for LPAR SSC06 to reach status(es) '['not-operating', 'exceptions']' timed out after 900 s - current status is 'operating'
```

Output in CLI:
```
Error: StatusTimeout: Waiting for LPAR SSC06 to reach status(es) '['not-operating', 'exceptions']' timed out after 900 s - current status is 'operating'
```

**To Reproduce**

1. Deactivate the LPAR

2. Run the zhmc client python command for lpar.activate(...)
```
lpar.activate(wait_for_completion=True, operation_timeout=None, status_timeout=None, allow_status_exceptions=True, activation_profile_name=None, force=True)
```

3. Wait for timeout

**Expected behavior**
Expected the zhmc client command to return with a successful REST API code upon completion of activation.

**Environment information**
* Output of `python -m zhmcclient.debuginfo`:
  `Operating system: Linux 4.19.121-linuxkit on x86_64`
`Python implementation: CPython 2.7.17 (64 bit, wide unicode)`
`Python version: 2.7.17`
`zhmcclient version: 0.30.0.dev1 `
* HMC version: 2.15
* HMC API version: 3.11

**Comment by andy-maier** [comment]
I'll look into this.

**Comment by andy-maier** [comment]
Hi Sean.
This happens because the zhmcclient tries to make up for a strange behavior of the HMC which is to report completion of the asynchronously proceeding activation even if the LPAR tatus does not show it yet. That causes subsequent commands to fail, when they depend on the new status. Therefore, in case of wait_for_completion, the zhmcclient library waits for the LPAR status to reach one of the desired status values before actually returning from the library call.

The data you posted shows that in this case, the LPAR activation went straight to status "operational". Normally, it goes to "non-operational" and a separate IPL is needed. I am not sure I fully understand when or why it does that, but in any case it should not hurt to add "operational" to the desired status values for activation.

I'll go ahead and do that. Stay tuned.

**Comment by andy-maier** [comment]
@sean-mills PR #758 fixes this. Can you please try that branch and see whether it solves the problem for you?

**Comment by sean-mills** [comment]
@andy-maier I just tried the branch and I confirm that the lpar activate does not timeout. Thank you.
