### ISSUE TITLE
Execute/Explore load-from-removable-media-or-server and/or any other arbitrary tasks

### ISSUE THREAD

**Issue by xnox** [zhmcclient/python-zhmcclient#80]
Hello,

I would like to use zhmclient to load LPAR from remote FTP server.

At first I have naively extended _lpar.py to add load_from_removable_media_or_server by calling session post on lpar_uri + '/operations/load-from-removable-media-or-server' with body encoding 'boot-device', 'boot-ftp-host', 'boot-ftp-username', 'boot-ftp-password', 'boot-ftp-insfile'.

However that results "no resource configured for URI".

I eventually browsed the task API and "found" that load-from-removable-media-or-server is '/api/console/tasks/b1126c6a-7417-415b-a724-d4b2b97464ed'. Better, but i'm still not able to invoke it against an lpar with a post method. Any URLs that I try to construct end up returning 404,1: No resource configured for URI.

Could load-from-removable-media-or-server be documented properly in the z Systems Hardware Management Console Web Services API?

Could it please be exposed as lpar_uri + /operations/load-from-removable-media-or-server'?

Or are there some other APIs that could list required body fields for a given task, and how to invoke post on it?

E.g. how does the UI console submit load-from-removable-media-or-server task?

I'm currently working against v2.13.0 HMC.

Regards,

Dimitri.

**Comment by andy-maier** [comment]
Hi Dimitri. Welcome!

I need to talk to the developers about this. Stay tuned.

**Comment by andy-maier** [comment]
@xnox
At this point, not all functions of the HMC GUI are available at the HMC Web Services API. The GUI tasks are not going through the HMC API, they take an internal path, and therefore it is possible that a GUI task is not externalized at the HMC API.

Specifically, the "Load From Removable Media or Server" GUI task is not currently available at the HMC API. We are discussing the request to add support for it.

One alternative would be to use DPM mode (Dynamic Partition Manager). In that mode, a lot more dynamic capabilities are available, e.g. for creating partitions and devices on these partitions. DPM mode can be set for each CPC individually and requires a restart of the CPC. Once the CPC is in DPM mode, the partition can be created such that it boots from an FTP server, by setting the "boot-ftp-host" and related properties in the "Create Partition" operation at the HMC API.

Enabling DPM mode as some prerequisites:
* HMC and SE must be on V2.13.1 (2.13.0 is not sufficient)
* The CPC in question must be at the firmware level corresponding to SE 2.13.1.
* The following features must be enabled on the CPC:
  - Feature code 0016: "Hardware for DPM" feature
  - 2 times feature code 0417: "OSA-Express 1000BASE-T Ethernet" feature (for primary and backup connectivity)

The HMC API book (referenced in the zhmcclient references section) is supposed to be complete as far as the functionality of the HMC API is concerned. Also, the request parameters are supposed to be properly documented in the HMC API book. If you find that any of that is not the case, please let us know (e.g. by opening an issue on the zhmcclient project; we'll pass it on to the authors of the book as a defect, as long as its not hundreds of them ;-)

Using the /api/console/tasks/... URI for this task is not going to work, because these URIs are used only when it comes to authorizing users for tasks (e.g. via the "Add Permission to User Role" operation). These URIs cannot be used to invoke these tasks.

**Comment by andy-maier** [comment]
Frank Heimes has opened issue #280 for this functionality, so I'm closing this issue here as a duplicate.
